### Base URL Test
GET http://localhost:5000

###### Authentication ######

### Register New User
POST http://localhost:5000/api/v1/auth/signup
Content-Type: application/json

{
    "name": "user",
    "email": "user12345@example.com",
    "password": "password12345"
}


### SignIn User
POST http://localhost:5000/api/v1/auth/signin
Content-Type: application/json

{
    "email": "user12345@example.com",
    "password": "password12345"
}


### Signout User
@authToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIxNjNkM2UyZS0yODQ0LTQzZTEtYjcxMC1jZWJlNTQ3ODJlMmMiLCJpYXQiOjE3MzE0OTY0NTIsImV4cCI6MTczMjEwMTI1Mn0.5mQRJlQ7eYoY1aAeEB1rW8rPmt_uG2fwXKSR7HCC0ow

GET http://localhost:5000/api/v1/auth/signout
Authorization: Bearer {{authToken}}


######### Tasks ##########

### Get All tasks
GET http://localhost:5000/api/v1/task
Authorization: Bearer {{authToken}}


### Create Task
POST http://localhost:5000/api/v1/task
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
    "title": "New Task",
    "description": "Finish the project and submit it on time."
}

### Update Task
@taskId = 6fb36053-4005-4ce9-8522-409bdf268ab0
PUT http://localhost:5000/api/v1/task/{{taskId}}
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
    "title": "Updated Complete project",
    "description": "Finish the project and submit it by next week.",
    "status": "in progress"
}


### Delete Task
DELETE http://localhost:5000/api/v1/task/{{taskId}}
Authorization: Bearer {{authToken}}
