### Base URL Test
GET http://localhost:5000

###### Authentication ######

### Register New User
POST http://localhost:5000/api/v1/auth/signup
Content-Type: application/json

{
    "name": "user",
    "email": "user123@example.com",
    "password": "password123"
}


### SignIn User
POST http://localhost:5000/api/v1/auth/signin
Content-Type: application/json

{
    "email": "user123@example.com",
    "password": "password123"
}


### Signout User
@authToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIxNjNkM2UyZS0yODQ0LTQzZTEtYjcxMC1jZWJlNTQ3ODJlMmMiLCJpYXQiOjE3MzE0OTExODksImV4cCI6MTczMjA5NTk4OX0.RKsCGfiF7izA9YhCAFjJPuNEOX4-VQtSQii6nmR5fHE
GET http://localhost:5000/api/v1/auth/signout
Authorization: Bearer {{authToken}}


######### Tasks ##########

### Get All tasks
GET http://localhost:5000/api/v1/task
Authorization: Bearer {{authToken}}


### Create Task
POST http://localhost:5000/api/v1/task
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
    "title": "Complete project",
    "description": "Finish the project and submit it on time."
}

### Update Task
@taskId = 0fb408e2-7419-4d5e-890f-73bc7a67b962
PUT http://localhost:5000/api/v1/task/{{taskId}}
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
    "title": "Updated Complete project",
    "description": "Finish the project and submit it by next week.",
    "status": "in progress"
}


### Delete Task
DELETE http://localhost:5000/api/v1/task/{{taskId}}
Authorization: Bearer {{authToken}}
